### ISSUE TITLE
Tutorial error: transaction mined but no correct result

### ISSUE THREAD

**Issue by zqzqz** [paritytech/pwasm-tutorial#33]
## environment
I exactly followed tutorial in step-4 to deploy and run the sample token contract.
Using Parity development chain. I set both gasLimit in pwasm-dev-chain and transaction to really high (>> 5000000). 

## steps
* Run scripts of step-4 in node console
* send deploy transaction
* send transfer transaction
* check balance

## expected result
* deploy returns contract instance with address
* transfer transaction sent and mined
* balance increases to 200

## actual result
Deploy works fine, it returns address. Though eth.estimateGas always throw rejection "transaction execution error"  
Transfer transaction is sent and mined  
```
2018-07-21 04:40:11  Transaction mined (hash 0xe40ed26f039d60204a07363ed4b7ce4a1ddac8d6e113af559cb550cea4dc8b1d)
2018-07-21 04:40:11  Imported #31 0x22ce…e34d (1 txs, 0.03 Mgas, 0 ms, 0.65 KiB)
```
The script  
```
web3.eth.personal.unlockAccount(web3.eth.defaultAccount, "user").then(() => TokenContract.methods.transfer("0x7BA4324585CB5597adC283024819254345CD7C62", 200).send()).then(console.log).catch(console.log);
``` 
triggers neither promise resolve nor reject (no console.log executed). The thread just keep running.
Balance doesn't increase. Return 0.  

## what I try
In the logic of token contract, it doesn't distribute any tokens to the owner (web.eth.defaultAccount). So is that means transfer transaction should be reverted? I am not sure about that so I added another simple function and called it. Some result.  
I set gas and gasLimit to very high. Same result.  
I tried both web3 1.0.0.Beta34 and web3 0.20.6. Same result.

**Comment by fckt** [comment]
hey, @zqzqz.  Could you attach your wasm binary you're deploying?

**Comment by zqzqz** [comment]
Sure.

**Comment by fckt** [comment]
I forgot to ask about version of Parity you use, sorry

**Comment by zqzqz** [comment]
```
➜  ~ parity --version
Parity
  version Parity/v1.11.6-beta-4ba600f-20180709/x86_64-linux-gnu/rustc1.27.0
Copyright 2015, 2016, 2017, 2018 Parity Technologies (UK) Ltd
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann
```

**Comment by fckt** [comment]
I just tried to use the last parity master and it works.. Looks like there is a bug is in the released Parity/v1.11.6-beta-4ba600f-20180709 version. I've tried version Parity/v1.11.7-stable though - doesn't work too.

Could I ask you to try to deploy it using the latest version from master branch (https://github.com/paritytech/parity-ethereum) to confirm that this problem is related to the released versions specifically?

You can run it like so:
```
cargo run --manifest-path=../parity/Cargo.toml -- --jsonrpc-apis all --chain wasm-dev-chain.json --unlock=0x004ec07d2329997267ec62b4166639513386f32e --password=passwd -l="own_tx=trace,txqueue=trace,wasm=trace,contract=trace,executive=trace,client=trace,external_tx=trace,miner=trace"
```

**Comment by zqzqz** [comment]
Parity-Ethereum/v2.1.0-unstable-7e6a571-20180720/x86_64-linux-gnu/rustc1.27.1
run the same script:
Parity error
```
Thread 'main' panicked at 'Integer overflow when casting U256', /home/zqz/.cargo/registry/src/github.com-1ecc6299db9ec823/ethereum-types-0.3.2/src/uint.rs:32
```
after
```
2018-07-22 02:29:59  main DEBUG own_tx  Imported to the pool (hash 0x1328c2663fb36a76ef570705100d22082da7d904b78c36db432d42ecccc0bd91)
2018-07-22 02:29:59  main DEBUG txqueue  [0x1328c2663fb36a76ef570705100d22082da7d904b78c36db432d42ecccc0bd91] Added to the pool.
2018-07-22 02:29:59  main DEBUG txqueue  [0x1328c2663fb36a76ef570705100d22082da7d904b78c36db432d42ecccc0bd91] Sender: 0x004e…f32e, nonce: 43, gasPrice: 0, gas: 5000000, value: 0, dataLen: 15831))
2018-07-22 02:29:59  main TRACE miner  update_sealing
2018-07-22 02:29:59  main TRACE miner  requires_reseal: sealing enabled
2018-07-22 02:29:59  main TRACE miner  requires_reseal: should_disable_sealing=false; forced=false, has_local=true, internal=Some(true), had_requests=false
2018-07-22 02:29:59  main TRACE miner  update_sealing: preparing a block
2018-07-22 02:29:59  main TRACE miner  prepare_block: No existing work - making new block
```

**Comment by fckt** [comment]
that's weird. Have you tried master (run using cargo run)?

**Comment by zqzqz** [comment]
```
git clone git@github.com:paritytech/parity-ethereum.git && cd parity-ethereum
```
in directory parity-ethereum
```
cargo run --manifest-path=./Cargo.toml -- --jsonrpc-apis all --chain wasm-dev-chain.json -l="own_tx=trace,txqueue=trace,wasm=trace,contract=trace,executive=trace,client=trace,external_tx=trace,miner=trace"
```
I deleted the 'unlock' option. (password 'user' cannot unlock the account 0x004ec...) It that matters?

**Comment by fckt** [comment]
> I deleted the 'unlock' option. (password 'user' cannot unlock the account 0x004ec...) It that matters?

It does. Check that you have a `--password=passwd` and the passwd file contains just

```
user
```

**Comment by zqzqz** [comment]
Yes tutorial code works well on latest parity.
Note that transfer method still cannot increase tokens of recipient. But my custom method can change the storage successfully. I suppose that is a minor logic error in step-4 example: we should distribute the defaultAccount some token before calling transfer.
Thank you @fckt

**Comment by zqzqz** [comment]
BTW, when I try to deploy my contract (which is more complex with x-contract-calls and payable functions), it always throw ```Error: The contract code couldn't be stored, please check your gas limit.``` If I increase gasLimit to ```1487626450060000``` (it's TOO high), there is the error: ```Error: Failed to check for transaction receipt:```. The wasm file is about 20.8 KB.
I suppose whether there is bugs in contract design should not influence deploy process. Sorry I can't attach my source code here. What is the possible causes? Too large binary file?

**Comment by fckt** [comment]
right, that's was a mistake in the tutorial itself. Contract code from step-4 is not quite functional. Fixed it https://github.com/paritytech/pwasm-tutorial/commit/6f20567f097ea1f285ce44acc8d73142db474297

Thanks for the feedback, @zqzqz
