### ISSUE TITLE
unable to compile cargo run

### ISSUE THREAD

**Issue by AchalaSB** [paritytech/pwasm-tutorial#36]
Im running some sample contracts, but getting an error. There is no cargo.toml in parent directory. 
Need help. Thanks in advance

: ~/PROJECT/pwasm-tutorial$ cargo run 
error: a bin target must be available for `cargo run`

**Comment by fckt** [comment]
Hey @AchalaSB! Thank you for your interest!
The contracts are not meant to run in the OS env. The contracts meant to be deployed and run on the Ethereum blockchain. I would suggest to go step-by-step, starting from https://github.com/paritytech/pwasm-tutorial#general-structure which would help you to get an idea.

**Comment by fckt** [comment]
Haven't you tried to run Parity with --jsonrpc-apis=all parameter?

**Comment by AchalaSB** [comment]
Tried. Im using my own account but still i got 

Error: Returned error: Unable to unlock the account.

**Comment by fckt** [comment]
> Tried. Im using my own account but still i got error. Its my first contract
> Error: Returned error: Unable to unlock the account.

But it's not the same error (which was `Error: Returned error: Method not found`), right?

The error `Error: Returned error: Unable to unlock the account.` is not related to the tutorial itself. The reason could be in the wrong password for your particular account.

For sake of tutorial I'd recommend you to use an account, provided in the tutorial (the one with the "user" password).

**Comment by kggp1995** [comment]
@AchalaSB , make sure that the account used to deploy the contract is unlocked.

This thread can be closed upon confirmation.
