### ISSUE TITLE
How JSON file and ABI is created?

### ISSUE THREAD

**Issue by AchalaSB** [paritytech/pwasm-tutorial#37]
1) I wanted to know how ABI is created for step-5 in the tutorial. So that I can do same for my contract (when I use ./build.sh wasm file and json is not created). Is there any other command?
2) What is the script (script.js) for getting ABI for any contract?

Thanks in Advance.

**Comment by fckt** [comment]
Hey @AchalaSB! Sorry for the late answer!
The JSON ABI is created here https://github.com/paritytech/pwasm-abi/blob/master/derive/src/lib.rs#L106 inside of the [`proc_macro`](https://doc.rust-lang.org/book/first-edition/procedural-macros.html)

**Comment by AchalaSB** [comment]
Thanks for reverting !
