### ISSUE TITLE
Wasm smart contracts code size seems much bigger than original EVM bytecode

### ISSUE THREAD

**Issue by btwear** [paritytech/pwasm-tutorial#39]
I followed the tutorial and deploy the contract of step-5 on my private chain.
Then I used web3 to check the binary by `eth.getCode()`, and I got a pretty big code.
I explored some other contracts on Etherscan, and the code size are much smaller than wasm contracts with similar source code line number.
If wasm contracts require 5~6 times the space to store them, it seems to be unacceptable.
Am I misunderstood something?

**Comment by fckt** [comment]
Yeah, unfortunately Wasm contracts can't be as compact as EVM ones. EVM was designed specifically for a use case, but Wasm uses a general-purpose byte code. Also, we have to statically link all the libs, used by the contract ATM. It haven't to have to be that way, though. In future it'll be possible to link libraries dynamically on execution, that'll reduce the contract size dramatically!
